# See https://github.com/golangci/golangci-lint#config-file
run:
  issues-exit-code: 1 #Default
  tests: true #Default

linters:
  enable:
    - misspell
    - gofmt
    - gosec
    - unconvert
    - gocyclo
    - goconst
    - goimports
    - gocritic

linters-settings:
  misspell:
    locale: US
    ignore-words:
      - cancelled
